apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
spec:
  type: NodePort
  selector:
    app: spring-petclinic
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30085
